apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-engine.fullname" . }}
  labels:
    {{- include "incident-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "incident-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incident-engine.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: incident-engine
    spec:
      serviceAccountName: {{ include "incident-engine.serviceAccountName" . }}
      containers:
        - name: incident-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "incident-engine.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
