apiVersion: 1

datasources:
  - name: Prometheus
    uid: argus-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: Loki
    uid: argus-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: argus-jaeger
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: "$${__value.raw}"

  - name: Jaeger
    uid: argus-jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
