apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingestion.yaml
  - stream-processor.yaml
  - drift-monitor.yaml
  - lakehouse-writer.yaml
  - orchestration.yaml
  - incident-engine.yaml
  - api-gateway.yaml
  - dashboard.yaml
  - observability.yaml
