apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argus-stream-processor
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argus
    argus.io/chart: stream-processor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hamidmatiny/Argus.git
    targetRevision: HEAD
    path: infra/helm/stream-processor
    helm:
      valueFiles:
        - values.yaml
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
