apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stream-processor.fullname" . }}
  labels:
    {{- include "stream-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stream-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stream-processor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: stream-processor
    spec:
      serviceAccountName: {{ include "stream-processor.serviceAccountName" . }}
      containers:
        - name: stream-processor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "stream-processor.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
